language: python
dist: xenial

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install: poetry install

script:
  - poetry run flake8 .
  - poetry run mypy flake8_eradicate.py
  - poetry run pytest
  - poetry check
  - poetry run pip check
  - poetry run safety check --bare --full-report

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
