[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "flake8-eradicate"
version = "1.0.0"
description = "Flake8 plugin to find commented out code"

license = "MIT"

authors = [
  "Nikita Sobolev <mail@sobolevn.me>"
]

readme = "README.md"

repository = "https://github.com/sobolevn/flake8-eradicate"
homepage = "https://github.com/sobolevn/flake8-eradicate"

keywords = [
  "flake8",
  "plugin",
  "linting",
  "wemake.services",
  "code quality"
]

classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Console",
  "Framework :: Flake8",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Quality Assurance",
]

[tool.poetry.plugins."flake8.extension"]
E8 = "flake8_eradicate:Checker"

[tool.poetry.dependencies]
python = "^3.6"

flake8 = "^3.5"
eradicate = "^2.0"
attrs = "*"

[tool.poetry.dev-dependencies]
pytest-cov = "^2.10"
pytest-randomly = "^3.4"
pytest = "^6.1"

flake8-print = "^3.1"
flake8-builtins = "^1.5"
flake8-commas = "^2.0"
flake8-quotes = "^3.2"
flake8-comprehensions = "^3.2"
flake8-docstrings = "^1.5"
flake8-string-format = "^0.3"
flake8-coding = "^1.3"
flake8-pep3101 = "^1.3"
flake8-super-call = "^1.0"
flake8-debugger = "^3.2"
flake8-isort = "^4.0"
pep8-naming = "^0.11"

mypy = "^0.790"
safety = "^1.9"

zipp = "3.3.0"
