[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"


[tool.poetry]
name = "flake8-eradicate"
version = "0.2.4"
description = "Flake8 plugin to find commented out code"

license = "MIT"

authors = [
  "Nikita Sobolev <mail@sobolevn.me>"
]

readme = "README.md"

repository = "https://github.com/sobolevn/flake8-eradicate"
homepage = "https://github.com/sobolevn/flake8-eradicate"

keywords = [
  "flake8",
  "plugin",
  "linting",
  "wemake.services",
  "code quality"
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Framework :: Flake8",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Software Development :: Quality Assurance",
]

[tool.poetry.plugins."flake8.extension"]
E8 = "flake8_eradicate:Checker"

[tool.poetry.dependencies]
python = "^3.6 || ^3.7"
flake8 = "^3.5"
eradicate = ">=0.2.1,<1.1.0"
attrs = ">=18.2,<20.0"

[tool.poetry.dev-dependencies]
pytest-cov = "^2.8"
pytest-randomly = "^3.1"
pytest = "^5.3"
flake8-pytest = "^1.3"
flake8-print = "^3.1"
flake8-builtins = "^1.4"
flake8-commas = "^2.0"
flake8-quotes = "^2.1"
flake8-comprehensions = "^3.1"
flake8-docstrings = "^1.5"
flake8-string-format = "^0.2"
flake8-coding = "^1.3"
flake8-bugbear = "^19.8"
flake8-pep3101 = "^1.3"
flake8-super-call = "^1.0"
flake8-debugger = "^3.2"
flake8-isort = "^2.8"
pep8-naming = "^0.9"
mypy = "^0.760"
safety = "^1.8"
